app = "openreader-webui"
primary_region = "ams"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3003
min_machines_running = 0
processes = ["app"]

[mounts]
source = "docstore"
destination = "/app/docstore"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
